name: Build

on:
  workflow_dispatch: {} # Enables the manual start

permissions:
  contents: write # Give permission to put the release into the repo

jobs:
  build-clients:
    runs-on: ubuntu-latest

    env:
      UserPass: '000' # It's password for pmos user

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pmbootstrap
        run: |
          git clone https://gitlab.postmarketos.org/postmarketOS/pmbootstrap.git
          mkdir -p ~/.local/bin
          ln -s "$PWD/pmbootstrap/pmbootstrap.py" ~/.local/bin/pmbootstrap
          PATH="$HOME/.local/bin:$PATH"
          pmbootstrap --version
        shell: bash

      - name: Copy config and init pmbootstrap (1)
        run: |
          mkdir -p ~/.config
          cp pmbootstrap_1.cfg ~/.config/pmbootstrap_v3.cfg
          yes '' | pmbootstrap init || true
        shell: bash

      - name: Build image (1)
        run: |
          printf '%s\n%s\n' "${{ env.UserPass }}" "${{ env.UserPass }}" | pmbootstrap install || true
          pmbootstrap shutdown
        shell: bash

      - name: Compress images (1)
        run: |
          sudo mv ~/.local/var/pmbootstrap/chroot_rootfs_qcom-msm8953/boot/lk2nd.img lk2nd.img
          sudo mv ~/.local/var/pmbootstrap/chroot_native/home/pmos/rootfs/qcom-msm8953.img qcom-msm8953.img
          sudo chmod 777 lk2nd.img
          sudo chmod 777 qcom-msm8953.img
          zip -9 -v PMOS_PlasmaMobile.zip lk2nd.img qcom-msm8953.img
          rm ~/.config/pmbootstrap_v3.cfg
          rm *.img
        shell: bash

      - name: Copy config and init pmbootstrap (2)
        run: |
          mkdir -p ~/.config
          cp pmbootstrap_2.cfg ~/.config/pmbootstrap_v3.cfg
          yes '' | pmbootstrap init || true
        shell: bash

      - name: Build image (2)
        run: |
          printf '%s\n%s\n' "${{ env.UserPass }}" "${{ env.UserPass }}" | pmbootstrap install || true
          pmbootstrap shutdown
        shell: bash

      - name: Compress images (2)
        run: |
          sudo mv ~/.local/var/pmbootstrap/chroot_rootfs_qcom-msm8953/boot/lk2nd.img lk2nd.img
          sudo mv ~/.local/var/pmbootstrap/chroot_native/home/pmos/rootfs/qcom-msm8953.img qcom-msm8953.img
          sudo chmod 777 lk2nd.img
          sudo chmod 777 qcom-msm8953.img
          zip -9 -v PMOS_Phosh.zip lk2nd.img qcom-msm8953.img
          rm ~/.config/pmbootstrap_v3.cfg
          rm *.img
        shell: bash

      - name: Create Release Info
        run: |
          DEVICE=$(grep '^device' pmbootstrap_1.cfg | cut -d'=' -f2 | xargs)
          SYSTEMD=$(grep '^systemd' pmbootstrap_1.cfg | cut -d'=' -f2 | xargs)
          UI1=$(grep '^ui' pmbootstrap_1.cfg | cut -d'=' -f2 | xargs)
          EXTRAS1=$(grep '^extra_packages' pmbootstrap_1.cfg | cut -d'=' -f2 | xargs | tr ',' ', ')
          UI2=$(grep '^ui' pmbootstrap_2.cfg | cut -d'=' -f2 | xargs)
          EXTRAS2=$(grep '^extra_packages' pmbootstrap_2.cfg | cut -d'=' -f2 | xargs | tr ',' ', ')

          {
            echo "Builded at: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            echo "Device: $DEVICE"
            echo "SystemD: $SYSTEMD"
            echo "User Password: ${{ env.UserPass }}"
            echo "-----"
            echo "DE: $UI1"
            echo "Extra: $EXTRAS1"
            echo "-----"
            echo "DE: $UI2"
            echo "Extra: $EXTRAS2"
          } > release_body.txt
        shell: bash

      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            PMOS*.zip
          tag_name: PostmarketOS
          draft: false
          body_path: release_body.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
